### ISSUE TITLE
 kvClient.GetValue: error: Method not found

### ISSUE THREAD

**Issue by hyacinthus** [0glabs/0g-storage-client#12]
Is this client match the testnet contract version?

**Comment by hyacinthus** [comment]
Thank you... you are right, so, is there a official kv node endpoint? Or do I still have to run a kv node myself?

**Comment by MiniFrenchBread** [comment]
Usually, users create key-value stream databases on the top of storage layer according to their needs, and then maintain KV nodes to monitor their own KV streams.

For more about how the KV works and how to run a KV node, please refer to following documents:
https://docs.0g.ai/0g-doc/docs/0g-storage/k-v-store
https://docs.0g.ai/0g-doc/run-a-node/storage-kv

**Comment by hyacinthus** [comment]
Thank you
