### ISSUE TITLE
rpc error: code = Unknown desc = execution reverted

### ISSUE THREAD

**Issue by browngres** [0glabs/0g-storage-client#39]
> FATA[2024-07-28T12:41:30+08:00] Failed to upload file
error="Failed to submit log entry: Failed to send transaction to append log entry: rpc error: code = Unknown desc = execution reverted"

Through debugging, it was found that the error came from the `estimateGasLimit` request, which is called when sending log entry transaction.
Located in this file 
`github.com/ethereum/go-ethereum@v1.14.7/accounts/abi/bind/base.go`

This error occurred while executing into this area:
```go
func (c *BoundContract) estimateGasLimit(opts *TransactOpts, contract *common.Address, input []byte, gasPrice, gasTipCap, gasFeeCap, value *big.Int) (uint64, error) {
	if contract != nil {
		// Gas estimation cannot succeed without code for method invocations.
		if code, err := c.transactor.PendingCodeAt(ensureContext(opts.Context), c.address); err != nil {
			return 0, err
		} else if len(code) == 0 {
			return 0, ErrNoCode
		}
	}
```

**Comment by MiniFrenchBread** [comment]
The recent update to the testnet contract has introduced the storage fee, and this error might be caused by the SDK not correctly calculating the fee. An incoming PR #40 will resolve this.

**Comment by browngres** [comment]
Thanks
