### ISSUE TITLE
Go build fails

### ISSUE THREAD

**Issue by crinard** [0glabs/0g-storage-client#42]
```go build```
```# github.com/0glabs/0g-storage-client```
```link: github.com/fjl/memsize: invalid reference to runtime.stopTheWorld```

**Comment by crinard** [comment]
It looks like this is a common issue: 
https://github.com/golang/go/issues/68167
https://github.com/bnb-chain/bsc/issues/2648
I used 1.26 and this worked fine.

**Comment by yorickdowne** [comment]
Go team rejected the memsize author’s proposal to make memsize work with Go 1.23.

Upstream go-ethereum fixed this by removing memsize in this patch: https://github.com/ethereum/go-ethereum/commit/e4675771eda550e7eeb63a8884816982c1980644
